=begin
#edna-srv

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ApplyDisguiseResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplyDisguiseResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::ApplyDisguiseResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplyDisguiseResponse' do
    it 'should create an instance of ApplyDisguiseResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::ApplyDisguiseResponse)
    end
  end
  describe 'test attribute "did"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
