#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require APP_PATH
require 'swagger_client'
Rails.application.require_environment!

User.inactive.each_with_index do |u, x|
    api_instance = SwaggerClient::DefaultApi.new
    body = SwaggerClient::ApplyDisguise.new() # ApplyDisguise |
    body.user = @u.id.to_s
    body.password = "" # No composition for decay
    body.disguise_json = File.read("disguises/data_decay.json").to_s
    body.tableinfo_json = File.read("disguises/table_info.json").to_s
    body.guisegen_json = File.read("disguises/guise_gen.json").to_s

    begin
      result = api_instance.apiproxy_apply_disguise(body)
      did = result.did

      DecayNotification.notify(@user, did).deliver_now
    rescue SwaggerClient::ApiError => e
      puts "Exception when calling DefaultApi->apiproxy_apply_disguise: #{e}"
    end
end
